### ISSUE TITLE
When i've failed more of 3 time, i don't get banned 

### ISSUE THREAD

**Issue by legabi** [Chewbaka69/fail2ban_pterodactyl#4]

**Comment by Chewbaka69** [comment]
please explain more your bug and show your config, without information
we can not help you

**Comment by legabi** [comment]
I've copy your config, don't work, i've added logpath, don't work too

**Comment by Chewbaka69** [comment]
you have installed fail2ban?
Are you on debian?

**Comment by legabi** [comment]
I've installed fail2ban and my other jails work, I'm on Ubuntu

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Chewbaka69** [comment]
did you run wings in daemon mode?

**Comment by legabi** [comment]
How do I know?

**Comment by Chewbaka69** [comment]
did you follow this step:
Daemonizing (using systemd)
https://pterodactyl.io/wings/1.0/installing.html#daemonizing-using-systemd

**Comment by legabi** [comment]
yes

**Comment by legabi** [comment]
oh my bad, i have multiple nodes ans on this node i don't have daemonizing

**Comment by legabi** [comment]
i've daemonizing but don't work too
Fail2ban restart ✅
Wings start with systemctl ✅

**Comment by Chewbaka69** [comment]
if you type this commmand:
journalctl -u wings

did you see something?

**Comment by Chewbaka69** [comment]
@legabi try to install this:
`apt install python-systemd`
or
`apt install python3-systemd`

**Comment by legabi** [comment]
i've installed, don't work. My logs: https://hastebin.com/uqetofalap.log

**Comment by Chewbaka69** [comment]
Ok so in your logs, i saw there is no `WARN:`
So wings did not detecte a failed connection with wrong credential.

Below an example of log with warn to ban ip:
`Nov 04 18:13:53 yourdomain.org wings[3545330]:  WARN: [Nov  4 18:13:53.199] failed to validate user credentials (invalid format) ip=X.X.X.X:45292 method=password subsystem=sftp username=ubnt`

That why there is no ban.
But for me the configuration is good
