### ISSUE TITLE
I cannot get it running

### ISSUE THREAD

**Issue by meganizer** [Chewbaka69/fail2ban_pterodactyl#5]
I'm getting the following error message while starting fail2ban after adding the pterodactyl files

Failed during configuration: Bad value substitution: option 'action' in section 'pterodactyl-sftp' contains an interpolation key 'logpath' which is not a valid option name. Raw value: '%(action_mwl)s'

**Comment by WouayNote** [comment]
The original `action_mwl` implies that fail2ban send the log by mail.
You can add `logpath = /var/log/pterodactyl/wings.log` in the `pterodactyl-sftp` jail.
However, pay attention to the size of this log file... it could be huge.
